spring.datasource.url=jdbc:postgresql://localhost:5542/accounts_db
spring.datasource.username=${ACCOUNTS_DB_USERNAME}
spring.datasource.password=${ACCOUNTS_DB_PASSWORD}
spring.datasource.hikari.maximum-pool-size=10

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.grpc.server.port=9102

spring.grpc.client.channels.auth.address=localhost:9101

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer