spring.application.name=gateway-service
server.port=8080

spring.grpc.client.channels.accounts.address=localhost:9102
spring.grpc.client.channels.auth.address=localhost:9101
spring.grpc.client.channels.kyc.address=localhost:9103
spring.grpc.client.channels.transfers.address=localhost:9104
spring.grpc.client.channels.ledger.address=localhost:9105

jwt.public-key-path=../../secrets/auth-public.pem

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
