ALTER TABLE cards ADD COLUMN IF NOT EXISTS daily_limit_cents BIGINT NOT NULL DEFAULT 0;
ALTER TABLE cards ADD COLUMN IF NOT EXISTS monthly_limit_cents BIGINT NOT NULL DEFAULT 0;
ALTER TABLE cards ADD COLUMN IF NOT EXISTS per_transaction_limit_cents BIGINT NOT NULL DEFAULT 0;

ALTER TABLE card_charges ADD COLUMN IF NOT EXISTS fee_cents BIGINT NOT NULL DEFAULT 0;
